#pragma once

//Dialog Windows
#define DIALOG_WINDOW_CANCEL 1
#define DIALOG_WINDOW_SAVE_MAP 2
#define DIALOG_WINDOW_SAVE_IIQ 3
#define DIALOG_WINDOW_SAVE_CS 4
#define DIALOG_WINDOW_SAVE_LEAGUE 5
#define DIALOG_WINDOW_UPDATE_CURRENCY 6
#define DIALOG_WINDOW_CHECKBOX_GENERAL 7
#define DIALOG_WINDOW_SAVE_OVERLAY_SETTINGS 8
#define DIALOG_WINDOW_PLUS_PROFIT 9
#define DIALOG_WINDOW_PLUS_SPENT 10
#define DIALOG_WINDOW_SAVELOC 11
#define DIALOG_WINDOW_CHECKBOX_TRASH 12

//Main Window
#define SETTINGS_MENU_MAP 51
#define SETTINGS_MENU_IIQ 52
#define FILE_MENU_EXIT 53
#define SETTINGS_MENU_CS 54
#define CURRENCY_MENU_UPDATE 55
#define SETTINGS_MENU_LEAGUE 56
#define SETTINGS_MENU_OVERLAY 57
#define FILE_MENU_RESET 58
#define HELP_ABOUT 59
#define HELP_TIPS 60